services:
  chess_dagster_postgres:
    image: postgres:11
    container_name: chess_dagster_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: "chess_dagster_postgres"
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    volumes:
      - ./data/dagster-postgres:/var/lib/postgresql/data

  chess_dagster_webserver:
    build:
      context: ./chess_dagster
      dockerfile: Dockerfile
    container_name: chess_dagster_webserver
    depends_on:
      - chess_dagster_postgres
    restart: always
    ports:
      - "3000:3000"
      - "8888:8888"
    expose:
      - "3000"
      - "8888"
    environment:
      POSTGRES_HOST: "chess_dagster_postgres"
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    env_file: .env
    volumes:
      - ./chess_dagster:/opt/dagster/app
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
  
  chess_dagster_daemon:
    build:
      context: ./chess_dagster
      dockerfile: Dockerfile
    container_name: chess_dagster_daemon
    depends_on:
      - chess_dagster_postgres
    restart: always
    environment:
      POSTGRES_HOST: "chess_dagster_postgres"
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    env_file: .env
    volumes:
      - ./chess_dagster:/opt/dagster/app
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    command: "dagster-daemon run"