services:
  chess_dagster:
    build:
      context: ./chess_dagster
      dockerfile: Dockerfile
    container_name: chess_dagster
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./data:/data
  superset:
      build:
        context: ./superset_dashboard
        dockerfile: Dockerfile
      container_name: superset
      environment:
        - ADMIN_USERNAME=admin
        - ADMIN_PASSWORD=admin
        - ADMIN_EMAIL=admin@superset.com
      ports:
        - 8088:8088
      volumes:
        - ./data:/app/superset_home