# https://github.com/dagster-io/dagster/blob/master/examples/deploy_docker/Dockerfile_user_code
# https://docs.astral.sh/uv/guides/integration/docker/#installing-uv
FROM python:3.10-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# ENV var
ENV PYTHONUNBUFFERED=1
ENV DAGSTER_HOME=/opt/dagster/dagster_home/
ENV DAGSTER_APP=/opt/dagster/app
ENV UV_PROJECT_ENVIRONMENT="/usr/local/"

# Download stockfish
# RUN apt-get update && apt-get install --no-install-recommends --assume-yes stockfish

# Create directory for dbt profile
RUN mkdir -p /root/.dbt

# Copy dbt profile
COPY profiles.yml /root/.dbt/profiles.yml

# Add data dir
RUN mkdir -p /data

# Add dagster yaml
RUN mkdir -p $DAGSTER_HOME
COPY dagster.yaml workspace.yaml $DAGSTER_HOME

# Add repo code
WORKDIR $DAGSTER_APP
COPY . .

# Install dependencies
RUN uv sync --extra dev

# Run dagster gRPC server on port 4000
EXPOSE 4000

# Start the dagster webserver
# https://github.com/dagster-io/dagster/discussions/14709
# dagster api grpc does not support dynamic code changes - requires restarting the container
# Use dagster code-server start to allow dynamic code changes when Reloding Definitions
# CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "chess_etl/definitions.py"]
CMD ["dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000", "-f", "chess_etl/definitions.py"]