chess_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ../../data/chess.duckdb
      threads: 1
    prod:
      type: duckdb
      path: "{{ env_var('CHESS_DB') }}"
      threads: 4
      module_paths:
        - "{{ env_var('DAGSTER_HOME') }}/chess_dbt/lib"
      plugins:
        # Custom module in the lib directory that defines SQL UDFs written in Python at the start of
        # the dbt run
        - module: my_custom_functions