chess_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('VSCODE_CWD') }}{{ env_var('CHESS_DB') }}"
      threads: 4
      module_paths:
        - "{{ env_var('VSCODE_CWD') }}/chess_dagster/chess_dbt/lib"
      plugins:
        # Custom module in the lib directory that defines SQL UDFs written in Python at the start of
        # the dbt run
        - module: my_custom_functions
    ci:
      type: duckdb
      path: ../../data/chess.duckdb
      threads: 1
      module_paths:
        - "./chess_dagster/chess_dbt/lib"
      plugins:
        # Custom module in the lib directory that defines SQL UDFs written in Python at the start of
        # the dbt run
        - module: my_custom_functions
    
    prod:
      type: duckdb
      path: "{{ env_var('CHESS_DB') }}"
      threads: 4
      module_paths:
        - "{{ env_var('DAGSTER_APP') }}/chess_dbt/lib"
      plugins:
        # Custom module in the lib directory that defines SQL UDFs written in Python at the start of
        # the dbt run
        - module: my_custom_functions