import os

ENABLE_PROXY_FIX = True
FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
    "DASHBOARD_NATIVE_FILTERS": True,
    "DASHBOARD_FILTERS_EXPERIMENTAL": True,
}
SECRET_KEY = os.getenv("SUPERSET_SECRET_KEY")