version: 2

models:
  - name: games
    config:
      pre_hook: "SET TimeZone = 'UTC';"
    columns:
      - name: uuid
      - name: url
      - name: rated
      - name: rules
      - name: time_class
      - name: game_mode
      - name: game_analysis_url
      - name: time_control
      - name: time_control_base
      - name: time_control_add_seconds
      - name: time_played_seconds
      - name: game_start_date
      - name: game_start_time
      - name: game_start_timestamp
      - name: game_end_timestamp
      - name: white__uuid
      - name: white__username
      - name: white__aid
      - name: white__rating
      - name: white__result
      - name: White_total_move_time
      - name: White_num_moves
      - name: black__uuid
      - name: black__username
      - name: black__aid
      - name: black__rating
      - name: black__result
      - name: black_total_move_time
      - name: black_num_moves
      - name: player_color
      - name: player_rating
      - name: player_result
      - name: player_total_move_time
      - name: player_num_moves
      - name: opponent_rating
      - name: opponent_result
      - name: opponent_total_move_time
      - name: opponent_num_moves
      - name: is_stronger_opponent
      - name: player_wdl
      - name: player_wdl_reason
      - name: initial_setup
      - name: fen
      - name: pgn
      - name: pgn_moves
      - name: pgn_move_extract
      - name: pgn_clock_extract
      - name: eco
      - name: eco_url
      - name: eco_name
      - name: checkmate_pieces
      - name: tcn
      - name: accuracies__white
      - name: accuracies__black