name: Docker CI Workflow

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-ci-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create .env file
      run: cp .env.example .env
    
    - name: Check docker-compose
      run: docker compose version

    - name: Check docker-compose format
      run: docker compose -f docker-compose.yml config
    
    - name: Install Make
      run: sudo apt-get install make
    
    - name: Build the docker compose images
      run: make build

    - name: Run python lint
      run: make lint-python
    
    - name: Run SQL lint
      run: make lint-sql

    - name: Run pytest
      run: make pytest
    
    - name: Run dbt unit test
      run: make dbt-unit-test
    
    - name: Run e2e
      run: make run
    
  generate-dbt-docs:
    runs-on: ubuntu-latest
    needs: run-ci-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: print working directory
        run: pwd

      - name: list directory
        run: ls -l
      
      - name: Install dbt
        run: pip3 install dbt-duckdb==1.9.0
      
      - name: Verify dbt
        run: dbt --version
      
      - name: dbt parse
        working-directory: ./chess_dagster/chess_dbt
        env:
          CHESS_USERNAME: johnnywhoopp
        run : |
          dbt parse --profiles-dir .. --project-dir . --target ci

      - name: generate dbt docs
        working-directory: ./chess_dagster/chess_dbt
        env:
          CHESS_USERNAME: johnnywhoopp
        run : |
          dbt docs generate --profiles-dir .. --project-dir . --empty-catalog --no-compile --target ci
          cd target
          mkdir ${{ github.workspace }}/docs
          cp *.json *.html ${{ github.workspace }}/docs
          ls -ltra ${{ github.workspace }}/docs 

      - name: "Upload pages to artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/docs
    
      - name: "Zip artifact"
        run: zip -jrq docs.zip ${{ github.workspace }}/docs
      
      - name: "Upload artifact for deployment job"
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs.zip
  
  # Deploy to Github pages
  deploy-to-github-pages:
    # Add a dependency to the build job
    needs: generate-dbt-docs
  
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
  
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
  
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or the latest "vX.X.X" version tag for this action