name: Docker CI Workflow

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    env:
      SUPERSET_SECRET_KEY: ${{ secrets.SUPERSET_SECRET_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create .env file
      run: cp .env.example .env
    
    - name: Check docker-compose
      run: docker compose version

    - name: Check docker-compose format
      run: docker compose -f docker-compose.yml config
    
    - name: Install Make
      run: sudo apt-get install make
    
    - name: Build the docker compose images
      run: make build

    - name: Run python lint
      run: make lint-python
    
    - name: Run SQL lint
      run: make lint-sql

    - name: Run Test
      run: make test
      
