name: Docker CI Workflow

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    env:
      SUPERSET_SECRET_KEY: ${{ secrets.SUPERSET_SECRET_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create .env file
      run: cp .env.example .env
    
    - name: Check docker-compose
      run: docker compose version

    - name: Check docker-compose format
      run: docker compose -f docker-compose.yml config
    
    - name: Install Make
      run: sudo apt-get install make
    
    - name: Build the docker compose images
      run: make build

    - name: Run python lint
      run: make lint-python
    
    - name: Run SQL lint
      run: make lint-sql

    - name: Run pytest
      run: make pytest
    
    - name: Run dbt unit test
      run: make dbt-unit-test
    
  generate-dbt-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: print working directory
        run: pwd

      - name: list directory
        run: ls -l
      
      - name: Install dbt
        run: pip3 install dbt-duckdb==1.9.0
      
      - name: Verify dbt
        run: dbt --version
      
      - name: dbt parse
        working-directory: ./chess_dagster/chess_dbt
        env:
          CHESS_USERNAME: johnnywhoopp
        run : |
          dbt parse --profiles-dir .. --project-dir .

      - name: generate dbt docs
        working-directory: ./chess_dagster/chess_dbt
        env:
          CHESS_USERNAME: johnnywhoopp
        run : |
          dbt docs generate --profiles-dir .. --project-dir . --empty-catalog --no-compile
          cd target
          mkdir ${{ github.workspace }}/docs
          cp *.json *.html graph.gpickle ${{ github.workspace }}/docs
          ls -ltra ${{ github.workspace }}/docs 

      - name: "Upload pages to artifact"
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ github.workspace }}/docs
    
      - name: "Zip artifact"
        run: zip -jrq docs.zip ${{ github.workspace }}/docs
      
      - name: "Upload artifact for deployment job"
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs.zip